### PR TITLE
Added serverless-finch and serverless-single-page-app plugins

### PR DESCRIPTION
**Pull request by Spiralfate**
Task description https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task2-serve-spa-aws/task.md

s3 bucket link: http://my-first-app-er-dev-serverlessdeploymentbucket-qssx9f2xal9u.s3-website-us-east-1.amazonaws.com/
Cf distribution link: https://dztvr97im9c4i.cloudfront.net/

### CODE REVIEW

**Comment by StashiKu** [comment]
it would be nice to put the comment above with the info about the current task, with links and scope of implemented work. Comfortable for reviewer. Up to you, it's just a proposal

**Comment by StashiKu** [comment]
unfortunately couldn't find in the markdown the required links for deployed app and s3 bucket 😞

**Comment by kirill-ianchuk** [comment]
@Spiralfate please add links to the configured resources

**Comment by slolkunchik** [comment]
s3 link returns 404 instead 403, fix it, please

**Pull request merged**
